sudo: required

services:
    - docker

language: python

python:
    - '2.7'

script:
    - ./pkg/travis.sh

env:
  matrix:
  - OS=ubuntu DIST=trusty PACK=deb
  - OS=el DIST=7 PACK=rpm
  - OS=fedora DIST=23 PACK=rpm
  - OS=debian DIST=jessie PACK=deb

notifications:
  email: false
  irc: false

deploy:
  provider: releases
  api_key: 
    secure: DxIsahov1cdPMmI2a8bAcmZKwvcYHlkvE//lrYXymC3ZWDv4/nrOyEi4V238lrHY9FppFMTL/W3d5NJoxrkCmyQRkFyWf/EKNttidxq/eDuiPxSloZYQqsQKIwWaUQ6QvgSzCY2xPJCh3PUOBWmGmOy9NsuS6FEX/NB10rJ1vi9u7jyelvK5D3rHIzlRQIHA/3DdsdW3+0alxCpvRyTqkR8P5G7UkreF3ah5dhkF936ZqzXOqa8PjigpEgB+UlvuevZqiruv2oK0XRYaHg4d2aVfsPyld7o4yTxsyRPEXqrab6XXoVd8FiyfuC1d1rKBnhWq8WJ5kfA7uaehQUOSKX6L/MghtEU3pTW96UKxudFUqPwweciEAljO10XyKlfP2GKtXDTYc2HxCY9AjT4ZVP1yoIAxNvhnVF2GERw45NOreDiMr2OpeUfHlxBM6b2GTRfFkCGlFoS/5TyUTEnQpU3nBe0b2vJf5SxAhGhJWSlWbQxTXeUmsEiJzAUw/rqeyxQYfTGTqMEoq4mb2EL9ADJnA2ciyatzC7KxVyCG0lC7ipuOzJnW67kav4uDUNLkIXpXex/Kxbmt30R3lcc+1wuU4kTsvytaf3wLmwct6NnkPe7inggSJXWYMoxfd+wbr5XPayJXMHDQtVUbs73mDiLvqear9H7W+fb3a7JstGA=
  file_glob: true
  file:
    - ../out/*.rpm
    - ../out/*.deb
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

