sudo: required

services:
    - docker

language: python

python:
    - '2.7'

script:
    - ./pkg/travis.sh

env:
  matrix:
  - OS=ubuntu DIST=trusty PACK=deb
  - OS=el DIST=7 PACK=rpm
  - OS=fedora DIST=23 PACK=rpm
  - OS=debian DIST=jessie PACK=deb

notifications:
  email: false
  irc: false

deploy:
  provider: releases
  api_key: 
    secure: jO7d9cHklX2k+eQXvX5v3ssmNWBhFPq4L+QkFQ21IZsc8boSp4LiEc6ZgvxClxf1Yvb1Pd84Xd71EbqB8hAW8Nu8e6Kb92Xdz+jmQU4kNBkNkvV5SGwkMnd100UupWH+6rGP0coWUDH535I+eUIDbCJcVua/5XgCXpeUGblo057OvNhCLkYitf0xy16OkSidERAoSakaAhr0AxMSpQm3OhzIUtIonyWuZGT4PST6uzQD07dGN9TLiNl39il5rz9LTm9kJ1iDGJ8mdN+I+9P/uTetuXLb4D8ON45Np3crk6bjWhTaz/sHS53Pjf/IVwe+msorQ4AjUia/ZiVmrKrFnZki+jzVo7VKaK1ip+RGImGWgY2J8fj4RIG3r9BNxtGEZkK/0Dkw6GVx461hyiVEi3wxSWUhgTXUI0oeK+/c0o2QQqEUvbIygB4j3IA5lNKxP3ASQ4Z6ETHDLWcX+DXnCy7xukYU9cCXTJbdGbAX4lZKtexjUQZReAv0KMXZY2HXPE6xV8ztSA1bOJoC+8kXgKBdO0EXo3MogwsoM9vCCgTvh2WY8smFDR1YA78f3tuYVwi1zl5OXRILdddy7PWiC+xSfxSCqY+rrItPnWH1RLqAxgUAMw33/IXgfQPqDDF6DaUirP5ZRUsEQUZKa92OlhDXXBO2iLNWh8AeMLZ42A0=
  file_glob: true
  file:
    - ../out/*.rpm
    - ../out/*.deb
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
